import { Head, useForm } from "@inertiajs/react";
import { useState } from "react";
import Navigation from "../Components/Navigation";

export default function AIVerification({ flash, aiResult }) {
    const { data, setData, post, progress, errors, processing } = useForm({
        image: null,
    });

    const [preview, setPreview] = useState(null);
    const [result, setResult] = useState(aiResult || null);
    const [loading, setLoading] = useState(false);

    const handleFileChange = (e) => {
        const file = e.target.files[0];
        if (file) {
            setData("image", file);
            const reader = new FileReader();
            reader.onloadend = () => {
                setPreview(reader.result);
            };
            reader.readAsDataURL(file);
            setResult(null);
        }
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        setLoading(true);
        post("/ai-verification", {
            forceFormData: true,
            onSuccess: (page) => {
                // Update result state with the AI result from the response
                if (page.props.aiResult) {
                    setResult(page.props.aiResult);
                }
                setLoading(false);
            },
            onError: () => {
                // Reset result on error
                setResult(null);
                setLoading(false);
            },
        });
    };

    const handleReset = () => {
        setData("image", null);
        setPreview(null);
        setResult(null);
        document.getElementById("image-upload").value = "";
    };

    return (
        <>
            <Head title="AI Verification - DWT Watermark" />

            <div className="min-h-screen bg-gray-50">
                <Navigation current="ai-verification" />

                {/* Header */}
                <header className="bg-white border-b border-gray-200">
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                        <h1 className="text-3xl font-bold text-gray-900">
                            AI Artwork Verification
                        </h1>
                        <p className="mt-2 text-sm text-gray-600">
                            Upload an image to check if it was generated by AI
                            or is a real artwork.
                        </p>
                    </div>
                </header>

                {/* Main Content */}
                <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                    <div className="grid grid-cols-1 gap-6">
                        {/* Upload Form */}
                        <div className="bg-white border border-gray-200 rounded-lg p-6">
                            <h2 className="text-lg font-medium text-gray-900 mb-4">
                                Upload Image
                            </h2>

                            <form onSubmit={handleSubmit} className="space-y-6">
                                {/* File Upload */}
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-2">
                                        Select Image
                                    </label>
                                    <div className="flex items-center justify-center w-full">
                                        <label
                                            htmlFor="image-upload"
                                            className="flex flex-col items-center justify-center w-full h-64 border-2 border-dashed border-gray-300 rounded-lg cursor-pointer bg-gray-50 hover:bg-gray-100 transition-colors"
                                        >
                                            <div className="flex flex-col items-center justify-center pt-5 pb-6">
                                                {preview ? (
                                                    <img
                                                        src={preview}
                                                        alt="Preview"
                                                        className="max-h-52 max-w-full object-contain rounded"
                                                    />
                                                ) : (
                                                    <>
                                                        <svg
                                                            className="w-10 h-10 mb-3 text-gray-400"
                                                            fill="none"
                                                            stroke="currentColor"
                                                            viewBox="0 0 24 24"
                                                        >
                                                            <path
                                                                strokeLinecap="round"
                                                                strokeLinejoin="round"
                                                                strokeWidth="2"
                                                                d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
                                                            />
                                                        </svg>
                                                        <p className="mb-2 text-sm text-gray-500">
                                                            <span className="font-semibold">
                                                                Click to upload
                                                            </span>{" "}
                                                            or drag and drop
                                                        </p>
                                                        <p className="text-xs text-gray-500">
                                                            PNG, JPG, GIF, WEBP
                                                            up to 10MB
                                                        </p>
                                                    </>
                                                )}
                                            </div>
                                            <input
                                                id="image-upload"
                                                type="file"
                                                className="hidden"
                                                accept="image/*"
                                                onChange={handleFileChange}
                                            />
                                        </label>
                                    </div>
                                    {errors.image && (
                                        <p className="mt-1 text-red-600 text-sm">
                                            {errors.image}
                                        </p>
                                    )}
                                </div>

                                {/* Buttons */}
                                <div className="flex gap-3">
                                    <button
                                        type="submit"
                                        disabled={
                                            !data.image || processing || loading
                                        }
                                        className="flex-1 px-4 py-2.5 bg-gray-900 text-white text-sm font-medium rounded-lg hover:bg-gray-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                                    >
                                        {loading
                                            ? "Verifying..."
                                            : "Verify AI Origin"}
                                    </button>
                                    {(preview || result) && (
                                        <button
                                            type="button"
                                            onClick={handleReset}
                                            className="px-4 py-2.5 bg-gray-200 text-gray-900 text-sm font-medium rounded-lg hover:bg-gray-300 transition-colors"
                                        >
                                            Reset
                                        </button>
                                    )}
                                </div>
                            </form>
                        </div>

                        {/* AI Verification Results */}
                        {result && (
                            <div className="bg-white border border-gray-200 rounded-lg p-6">
                                <h2 className="text-lg font-medium text-gray-900 mb-4">
                                    AI Detection Result
                                </h2>

                                <div
                                    className={`p-4 rounded-lg border ${
                                        result.isAI
                                            ? "bg-red-50 border-red-200"
                                            : "bg-green-50 border-green-200"
                                    }`}
                                >
                                    <div className="flex items-start">
                                        <div className="flex-shrink-0">
                                            {result.isAI ? (
                                                <svg
                                                    className="w-6 h-6 text-red-600"
                                                    fill="none"
                                                    stroke="currentColor"
                                                    viewBox="0 0 24 24"
                                                >
                                                    <path
                                                        strokeLinecap="round"
                                                        strokeLinejoin="round"
                                                        strokeWidth="2"
                                                        d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                                                    />
                                                </svg>
                                            ) : (
                                                <svg
                                                    className="w-6 h-6 text-green-600"
                                                    fill="none"
                                                    stroke="currentColor"
                                                    viewBox="0 0 24 24"
                                                >
                                                    <path
                                                        strokeLinecap="round"
                                                        strokeLinejoin="round"
                                                        strokeWidth="2"
                                                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                                                    />
                                                </svg>
                                            )}
                                        </div>
                                        <div className="ml-3 flex-1">
                                            <h3
                                                className={`text-sm font-medium ${
                                                    result.isAI
                                                        ? "text-red-800"
                                                        : "text-green-800"
                                                }`}
                                            >
                                                {result.isAI
                                                    ? "🤖 AI-Generated Artwork Detected"
                                                    : "🎨 Real Artwork Detected"}
                                            </h3>
                                            <div
                                                className={`mt-2 text-sm ${
                                                    result.isAI
                                                        ? "text-red-700"
                                                        : "text-green-700"
                                                }`}
                                            >
                                                <p>{result.message}</p>
                                                {result.details && (
                                                    <p className="mt-1 text-xs font-mono bg-white bg-opacity-50 p-2 rounded">
                                                        {result.details}
                                                    </p>
                                                )}

                                                {/* Enhanced Metrics Display */}
                                                {result.confidence && (
                                                    <div className="mt-3 space-y-2">
                                                        <div className="flex items-center justify-between text-xs">
                                                            <span className="font-medium">
                                                                Confidence
                                                                Level:
                                                            </span>
                                                            <span
                                                                className={`px-2 py-1 rounded font-semibold ${
                                                                    result.confidence ===
                                                                    "HIGH"
                                                                        ? "bg-red-200 text-red-900"
                                                                        : result.confidence ===
                                                                          "MEDIUM"
                                                                        ? "bg-yellow-200 text-yellow-900"
                                                                        : "bg-green-200 text-green-900"
                                                                }`}
                                                            >
                                                                {
                                                                    result.confidence
                                                                }
                                                            </span>
                                                        </div>

                                                        {result.detection_score !==
                                                            undefined && (
                                                            <div className="flex items-center justify-between text-xs">
                                                                <span className="font-medium">
                                                                    AI Score:
                                                                </span>
                                                                <span className="font-mono">
                                                                    {result.detection_score.toFixed(
                                                                        2
                                                                    )}{" "}
                                                                    / 10.00
                                                                </span>
                                                            </div>
                                                        )}

                                                        {result.confidence_percentage !==
                                                            undefined && (
                                                            <div className="flex items-center justify-between text-xs">
                                                                <span className="font-medium">
                                                                    Confidence:
                                                                </span>
                                                                <span className="font-mono">
                                                                    {
                                                                        result.confidence_percentage
                                                                    }
                                                                    %
                                                                </span>
                                                            </div>
                                                        )}

                                                        {/* Visual Score Bar */}
                                                        {result.detection_score !==
                                                            undefined && (
                                                            <div className="mt-2">
                                                                <div className="flex justify-between text-xs mb-1">
                                                                    <span className="font-medium">
                                                                        AI
                                                                        Probability:
                                                                    </span>
                                                                    <span className="text-xs text-gray-600">
                                                                        {result.isAI
                                                                            ? "Above Threshold"
                                                                            : "Below Threshold"}
                                                                    </span>
                                                                </div>
                                                                <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden relative">
                                                                    {/* Threshold line */}
                                                                    <div className="absolute left-[50%] top-0 bottom-0 w-0.5 bg-red-500 z-10"></div>
                                                                    {/* Score bar */}
                                                                    <div
                                                                        className={`h-3 rounded-full transition-all ${
                                                                            result.isAI
                                                                                ? "bg-red-600"
                                                                                : "bg-green-600"
                                                                        }`}
                                                                        style={{
                                                                            width: `${Math.min(
                                                                                (result.detection_score /
                                                                                    10) *
                                                                                    100,
                                                                                100
                                                                            )}%`,
                                                                        }}
                                                                    ></div>
                                                                </div>
                                                                <div className="flex justify-between text-xs mt-1 text-gray-500">
                                                                    <span>
                                                                        0
                                                                    </span>
                                                                    <span className="text-red-600 font-medium">
                                                                        ↑
                                                                        Threshold
                                                                        (5.0)
                                                                    </span>
                                                                    <span>
                                                                        10
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        )}

                                                        {/* Features Analyzed */}
                                                        {result.features_analyzed && (
                                                            <div className="mt-4 pt-3 border-t border-gray-300">
                                                                <span className="text-xs font-medium block mb-2">
                                                                    Features
                                                                    Analyzed:
                                                                </span>
                                                                <div className="grid grid-cols-2 gap-2 text-xs">
                                                                    {Object.entries(
                                                                        result.features_analyzed
                                                                    ).map(
                                                                        ([
                                                                            feature,
                                                                            score,
                                                                        ]) => (
                                                                            <div
                                                                                key={
                                                                                    feature
                                                                                }
                                                                                className="flex justify-between"
                                                                            >
                                                                                <span className="capitalize">
                                                                                    {feature.replace(
                                                                                        "_",
                                                                                        " "
                                                                                    )}
                                                                                    :
                                                                                </span>
                                                                                <span className="font-mono">
                                                                                    {
                                                                                        score
                                                                                    }
                                                                                    %
                                                                                </span>
                                                                            </div>
                                                                        )
                                                                    )}
                                                                </div>
                                                            </div>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {/* Information Box */}
                                <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                                    <h4 className="text-sm font-semibold text-blue-900 mb-2">
                                        ℹ️ About AI Detection
                                    </h4>
                                    <p className="text-xs text-blue-800">
                                        This analysis uses machine learning to
                                        detect patterns typical of AI-generated
                                        artworks. Results are probabilistic and
                                        may not be 100% accurate. The model
                                        analyzes texture patterns, color
                                        distribution, edge consistency, and
                                        other features to make its
                                        determination.
                                    </p>
                                    {result.model_used && (
                                        <p className="text-xs text-blue-700 mt-2">
                                            <strong>Model:</strong>{" "}
                                            {result.model_used}
                                        </p>
                                    )}
                                    {result.analysis_time && (
                                        <p className="text-xs text-blue-700">
                                            <strong>Analysis Time:</strong>{" "}
                                            {result.analysis_time}ms
                                        </p>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* Loading State */}
                        {loading && !result && (
                            <div className="bg-white border border-gray-200 rounded-lg p-12">
                                <div className="flex flex-col items-center justify-center">
                                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900 mb-4"></div>
                                    <p className="text-gray-600">
                                        Analyzing image for AI generation...
                                    </p>
                                </div>
                            </div>
                        )}
                    </div>
                </main>
            </div>
        </>
    );
}
